config/routes.rb
Rails.application.routes.draw do

  root 'pages#root'

  get 'payment' => 'pages#payment'
  get 'about' => 'pages#about', as: 'about'
  get 'personal-order' => 'pages#uniq', as: 'personal_order'
  get 'tags' => 'tags#list'
  get 'sitemap' => 'pages#sitemap'
  get 'items/new' => 'products#new'

  post 'personal-order' => 'pages#make_uniq'
  post 'user' => 'user#register', :as => :user
  post 'subscriptions/new', as: 'new_subscription'

  scope :profile do
    get  '' => 'user#profile', as: 'profile'
    post '' => 'user#update'
  end

  scope :blog do
    get '' => 'blog#index', as: 'blog'
    get 'article/:id/:title' => 'blog#show', as: 'blog_article'
    resources :articles, only: [:new, :destroy] do
      post '' => 'articles#update', on: :member
    end
  end

  resources :products, path: 'items', except: [:new, :edit, :create, :show] do
    delete '/image/:id' => 'products#delete_image', on: :member
    post '/images' => 'products#reorder_images', on: :member
    get '/:name' => 'store#index', as: 'item'
    post '/:product_name' => 'products#update', on: :member
    get '' => 'products#get', on: :member
  end

  scope :store do
    get 'new' => 'store#new', as: :new_product
    get '' => 'store#index', as: :store
    get 'get' => 'store#get'
    resources :categories, path: 'collections', only: [:index, :new] do
      get ':url_name' => 'categories#show', as: 'collection'
      get '' => 'categories#show'
      post ':url_name' => 'categories#update'
      delete ':url_name' => 'categories#destroy'
    end
    resources :specials, only: [:index, :new] do
      get ':url_name' => 'specials#show', as: 'special'
      get '' => 'specials#show'
      post ':url_name' => 'specials#update'
      delete ':url_name' => 'specials#destroy'
    end
    get '/:tag' => 'store#index'
  end

  resources :cart, only: [:index, :new, :destroy] do
    get 'checkout', on: :collection
  end

  resources :reviews, only:  [:index, :create, :destroy]
  resources :orders, except: [:update, :edit]

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'login' => 'users/sessions#new', :as => :new_user_session
    post 'login' => 'users/sessions#create', :as => :user_session
    delete 'logout' => 'users/sessions#destroy', :as => :destroy_user_session
    get 'logout' => 'users/sessions#destroy'
  end

  %w( 404 422 500 503 ).each do |code|
    get code, :to => 'errors#show', :code => code
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name, :price

  has_and_belongs_to_many :tags
  has_many :cart_entries
  has_many :orders, :through => :cart_entries
  has_many :images, as: :imageable, dependent: :destroy
  belongs_to :category

  def self.default
    Product.create name: 'Назови меня', price: 0, stock: 0
  end

  def to_param
    "#{id}/#{name}"
  end

  def url_name
    self.name.gsub ' ', '_'
  end

  def get_json
    self.to_json(:include => [:images, :category, {:tags => { :include =>  :special  } }]).html_safe
  end

  def <=>(this)
    self.created_at <=> this.created_at
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:update, :destroy]
  before_action :authenticate_admin!, only: [:update, :destroy]

  def get
    @product = Product.find params[:id]
  end

  def show
    redirect_to store_path
  end

  def update
    begin
      add_images
      render nothing: true
      return
    end if params[:images]

    update_tags if params[:tags]
    update_category if params[:category]
    @product.update(product_params)
    print product_params[:description]
    render nothing: true
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  def delete_image
    @id = params[:id]
    Image.destroy(@id)
  end

  def reorder_images
    counter = 0
    params[:order].each do | image_id |
      Image.find(image_id).update(order: counter)
      counter += 1
    end
    render nothing: true
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def update_tags
    @product.tags.clear
    params[:tags].each do | tag_name |
      tag = Tag.find_by_name(tag_name) || Tag.create(name: tag_name)
      @product.tags << tag
    end if params[:tags].length > 0
    Tag.cleanup
  end

  def update_category
      @product.category = Category.find_by_name params[:category]
      @product.save
  end

  def add_images
    params[:images].each do | file |
      image = @product.images.build
      image.update file: file
      errors = image.errors
    end
    @product.save
  end

  def product_params
    params.permit(:name, :price, :description, :stock)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def tag_string(product)
    product.tags.map(&:name).join ' '
  end

  def category_for(product)
    product.category ? product.category.name : '';
  end

  def search_result(products)
    products.empty? ? 'products/emptySearch' : products
  end

  def description_for(product)
    product.description.length > 0 ? product.description : lorem
  end

  def product_url(product)
    product_item_path(product.id, product.url_name)
  end
end

app/views/products/_grid.erb
<div class="products <%= grid_size %> grid clear">
  <% products.each do | product | %>
    <div class="grid-cell">
      <%= render product %>
    </div>
  <% end %>
</div>

app/views/products/_product.erb
<% if not defined?(context) %>
    <div class='product open-modal' data-modal='product-show' data-arg='<%= product.id %>'>
      <div class="product-data">
        <img class="product-image cover" src="<%= image_for(product, 'thumb') %>" alt="<%= product.name %>"/>
        <div class="product-info">
          <h3><%= product.name %></h3>
          <p class="price font-accent"><%= price(product.price) %></p>
          <span class="link">Подробнее <span class="arrow right brown long"></span></span>
        </div>
      </div>
    </div>
<% elsif context == 'cart' %>
    <div class="cart-product" data-id = '<%= product.id %>' data-type="<%= type %>">
      <div class='img-container'>
        <img class = 'cover' src="<%= product_image(product).file.thumb.url %>" alt="<%= product.name %>"/>
      </div>
      <div class="details">
        <h4 class="title">
          <%= product.name %>
          <%= link_to cart_path(id: product.id, type: type), remote: true, method: 'delete' do %>
            <img class='remove' src="<%= image_url 'cross_white.png' %>" alt=""/>
          <% end %>
        </h4>
        <%= render partial: 'UI/counter', locals: {val: amounts[product.id]} %>
        <span class='price'><%= product.price %></span>
      </div>
    </div>
<% end %>

app/views/products/delete_image.js.erb
$('.edit-images .img-cnt[data-id="<%= @id %>"]').remove();

app/views/products/get.js.erb
<%= @product.get_json %>

app/views/products/hot.erb
<% content_for :javascripts do %>
    <%= javascript_include_tag 'pages/hot' %>
<% end %>

<div class="ui hot container clear">
  <div class="collection-cnt">
    <div class="collection image-container" style='background-image: url(<%= image_for @collection %>)'></div>
    <div class="collection-info">
      <h2><%= @collection.name %></h2>

      <p><%= @collection.description %></p>
    </div>
    <div class="button-container">
      <a href="<%= url_for @collection %>" class='button next-collection' data-remote="true">Следующая коллекция</a>
    </div>
  </div>
  <div class="products-cnt">
    <%= render partial: @products %>
    <a href="<%= products_url %>">
      <div class="button-container">
        <span class='link-to-store'>Просмотр каталога →</span>
      </div>
    </a>
  </div>
  <div class="special-cnt">
    <% if @special %>
        <div class="special image-container" style='background-image: url(<%= image_for @special %>)'></div>
        <div class="special-info">
          <h2><%= @special.title %></h2>

          <p><%= @special.description %></p>
        </div>
        <div class="button-container">
          <a href="<%= url_for @special %>" class='button next-specials' data-remote="true">Следующая акция</a>
        </div>
    <% end %>
  </div>
</div>
<%= render partial: 'products/productModal' %>
<% content_for :javascripts do %>
    <%= render partial: 'products/json', locals: {products: @products} %>
<% end %>